openapi: 3.0.1
info:
  title: Lab Configuration Generation
  description: '
  This API is built on the cbaxter1988/lcg package, providing the ability to generate various device configurations
  '
  version: 1.0.0
servers:
  - url: 'http://udev.bits.local:5002/api'
paths:
  /v1/lcg/config/base:

    post:
      tags:
        - Config
      summary: Generates Base Configurations.
      description: '
      Creates Base Configurations based on the node_type key.
      '
      parameters:
        - in: query
          description: Node type you would like generated.
          name: node_type
          schema:
            type: string
            enum:
              - ios_rtr

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseConfig'
              
      responses:
        '200':
          description: OK
tags:
  - name: Config

components:
  schemas:
    BaseConfig:
      $ref: 'openapi/schemas/base_config.yml#/BaseConfig'